BlockLimit: 100
BlockList:
  - Material.DIRT
  - Material.GRASS_BLOCK
  - Material.STONE
DelaySeconds:
  DelayBetweenMessage: 1000
  DelayResetCounter: 1000
WorldList:
  - World1
  - World2
messages:
  alert:
    title: "Tu as min√© beaucoup de block !"
    subtitle: "Je te rappelle que tu es dans le monde %world_name_<world>% "
permission : detection.bypass


