# Limite de block au delà de laquelle le joueur reçoit une alerte
# /!\ Seulement des entiers positifs /!\
BlockLimit: 100

# Liste des blocks pris en compte pour la détection
BlockList:
  - DIRT
  - GRASS_BLOCK
  - STONE

# Différents délai utiles au plugin (tous exprimés en seconde)
DelaySeconds:
  # Délai qui s'écoule entre 2 messages d'alerte
  DelayBetweenMessage: 30
  # Délai qu'il faut pour une remise à 0 du compteur
  DelayResetCounter: 180

# Liste des mondes pris en compte dans la détection
WorldList:
  - world
  - World2

Messages:
  Alert:
    Title : "&cYou mined too many blocks"
    Subtitle: "&7&oDon't forget you are in the world &e&o%worldName%"
  BadArguments: "&bPlugin&3Detection &8→ &cThere's an error in the command."
  ReloadComplete: "&bPlugin&3Detection &8→ &aPlugin reloaded without error."

Debug: false
ClearPlayersTimesOnReload: false




